---
# Variables por defecto para el rol de wordpress
wordpress_db_name: ""
wordpress_db_user: ""
wordpress_db_pass: ""
wordpress_db_host: ""
wordpress_version: ""
wordpress_site_title: ""
wordpress_admin_user: ""
wordpress_admin_pass: ""
wordpress_admin_email: ""
wp_install_dir: "/var/www/html"
php_packages:
  - php
  - libapache2-mod-php
  - php-mysql
  - php-curl
  - php-gd
  - php-mbstring